# 主题配置
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00c4b6"
  button_hover: "#FF7242"
  text_selection: "#00c4b6"
  link_color: "#99a9bf"
  meta_color: "#858585"
  hr_color: "#A4D8FA"
  code_foreground: "#F47466"
  code_background: "rgba(27, 31, 35, .05)"
  toc_color: "#00c4b6"
  blockquote_padding_color: "#49b1f5"
  blockquote_background_color: "#49b1f5"

background: url(https://i.loli.net/2019/09/09/5oDRkWVKctx2b6A.png)
footer_bg: true

preloader: true
index_top_img_height: 400px

activate_power_mode:
  enable: true
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false

canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false  #設置是否每次點擊都更換綵帶
  mobile: false # false 手機端不顯示 true 手機端顯示

beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: "#F47466"

font:
  global-font-size:
  code-font-size:
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: consolas, Menlo, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif

# 顶部菜单配置
menu:
  首页: / || fa fa-home
  时间轴: /archives/ || fa fa-archive
  标签: /tags/ || fa fa-tags
  分类: /categories/ || fa fa-folder-open
  媒体||fas fa-list:
    - 番剧 || /bangumis/ || fab fa-youtube
    - 电影 || /movies/ || fa fa-film
    - 书单 || /books/ || fas fa-book
    - 音乐 || /music/ || fa fa-music
  友链: /link/ || fa fa-link
  关于: /about/ || fa fa-heart


# 代码显示配置
highlight_theme: mac # default / darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
code_word_wrap: false

# 复制内容（后面加上版权信息）
copy:
  enable: true
  copyright:
    enable: true
    limit_count: 50

# 社交配置
social:
  fab fa-github: https://github.com/livissnack || Github
  fas fa-envelope: mailto:brucesnack@gmail.com || Email

post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

post_copyright:
  enable: true
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 配置二维码打赏
reward:
  enable: true
  QR_code:
    - img: /image/wechat.jpg
      link:
      text: 微信
    - img: /image/alipay.jpg
      link:
      text: 支付宝

# 修改侧边card里面的图像
avatar:
  img: /image/avatar.png
  effect: true

# 顶部@信息
footer:
  owner:
    enable: true
    since: 2020

# 访问人数统计
busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

# 发布日期
runtimeshow:
  enable: true
  publish_date: 12/30/2020 00:00:00

# 分享设置
sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq

# 去掉聊天按钮
chat_btn: false

# Valine评论系统设置
comments:
  use:
    - Valine
  text: true
  lazyload: true
  count: true
valine:
  appId: SrhoU1q5wRvrvU2rARpXxa03-MdYXbMMI # leancloud application app id
  appKey: 7gO3WzCVfy3aLymIvuHUPNjw # leancloud application app key
  pageSize: 10 # comment list page size
  avatar: monsterid # gravatar style https://valine.js.org/#/avatar
  lang: zh-CN # i18n: zh-CN/zh-TW/en/ja
  placeholder: 记得留下你的昵称和邮箱....可以快速收到回复 # valine comment input placeholder(like: Please leave your footprints )
  guest_info: nick,mail,link #valine comment header info (nick/mail/link)
  emojiCDN: 
  requiredFields: nick,mail # required fields (nick/mail)
  option:

# 配置侧边聊天系统
chatra:
  enable: true
  id: FLjhrao4Pvp735JSB

# google广告创收
google_adsense:
  enable: true
  auto_ads: true
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: # 填入個人識別碼
  enable_page_level_ads: true

CDN:
  # comments
  valine: https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/Valine.min.js